const wordData = [
  { word: "前年", pinyin: "qiánnián", meaning: "the year before last; two years ago" },
  { word: "包", pinyin: "bāo", meaning: "bag; package" },
  { word: "當地", pinyin: "dāngdì", meaning: "local; from the area" },
  { word: "名產", pinyin: "míngchǎn", meaning: "local specialty; famous local product" },
  { word: "明信片", pinyin: "míngxìnpiàn", meaning: "postcard" },
  { word: "訂", pinyin: "dìng", meaning: "to reserve; to book; to order" },
  { word: "免費", pinyin: "miǎnfèi", meaning: "free of charge" },
  { word: "無線網路", pinyin: "wúxiàn wǎnglù", meaning: "Wi-Fi; wireless Internet" },
  { word: "美麗", pinyin: "měilì", meaning: "beautiful" },
  { word: "美", pinyin: "měi", meaning: "pretty; beautiful" },
  { word: "毛", pinyin: "máo", meaning: "dime; ten cents (spoken)" },
  { word: "讓", pinyin: "ràng", meaning: "to let; to allow; to make (someone feel)" },
  { word: "正在", pinyin: "zhèngzài", meaning: "in the middle of doing something" },
  { word: "公路", pinyin: "gōnglù", meaning: "highway; main road" },
  { word: "石頭", pinyin: "shítou", meaning: "stone; rock" },
  { word: "掉", pinyin: "diào", meaning: "to drop; to fall off" },
  { word: "下來", pinyin: "xiàlai", meaning: "to come down" },
  { word: "一下子／一下子兒", pinyin: "yíxiàzi / yíxiàzir", meaning: "in a moment; suddenly" },
  { word: "光", pinyin: "guāng", meaning: "used up; nothing left" },
  { word: "鐵路", pinyin: "tiělù", meaning: "railway" },
  { word: "鐵", pinyin: "tiě", meaning: "iron; metal" },
  { word: "網頁", pinyin: "wǎngyè", meaning: "web page" },
  { word: "訂位", pinyin: "dìngwèi", meaning: "to reserve a seat; to book a seat" },
  { word: "底", pinyin: "dǐ", meaning: "bottom; base; end of something" },
  { word: "出發", pinyin: "chūfā", meaning: "to depart; to set out" },
  { word: "國家公園", pinyin: "guójiā gōngyuán", meaning: "national park" },
  { word: "爬", pinyin: "pá", meaning: "to climb; to hike; to crawl" },
  { word: "座位", pinyin: "zuòwèi", meaning: "seat" },
  { word: "位子", pinyin: "wèizi", meaning: "seat; place (informal)" },
  { word: "記", pinyin: "jì", meaning: "to remember; to write down" },
  { word: "日期", pinyin: "rìqí", meaning: "date (calendar)" }
];